[project]
name = "sitn"
version = "0.1.0"
description = "Code for OOD detection experiments with flow matching."
readme = "README.md"
authors = [
    { name = "philipp", email = "72914813+bomatter@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "filelock>=3.16.0",
    "flow-matching>=1.0.10",
    "gdown>=5.2.1",
    "ipykernel>=7.1.0",
    "ipynbname>=2025.8.0.0",
    "matplotlib>=3.10.7",
    "nb-clean>=4.0.1",
    "numpy>=2.3.4",
    "pandas>=2.3.3",
    "pip>=25.3",
    "pyyaml>=6.0.3",
    "scikit-learn>=1.7.2",
    "seaborn>=0.13.2",
    "statsmodels>=0.14.6",
    "timm>=1.0.26",
    "torch>=2.9.0",
    "torchmetrics>=1.8.2",
    "torchvision>=0.24.0",
    "tqdm>=4.67.1",
    "wandb>=0.22.3",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchvision = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]
torchaudio = [
  { index = "pytorch-cu128", marker = "sys_platform == 'linux' or sys_platform == 'win32'" },
]

[tool.ruff]
line-length = 120
extend-include = ["*.ipynb"]  # include notebooks in linting

[tool.ruff.lint]
select = [
    "E",   # pycodestyle errors (formatting, spacing)
    "W",   # pycodestyle warnings (minor formatting issues)
    "F",   # pyflakes (catches unused imports, undefined variables)
    "I",   # isort (sorts and groups imports)
    "UP",  # pyupgrade (updates old Python syntax to modern syntax)
    "B",   # flake8-bugbear (catches common logic bugs)
]

ignore = [
    "E501",  # ignore line length in linter (handled by formatter)
]

[project.scripts]
sitn = "sitn:main"
sitn-preprocess = "sitn.datasets.dataset_factory:main"
sitn-train = "sitn.train:main"
sitn-eval = "sitn.evaluate:main"

[build-system]
requires = ["uv_build>=0.9.7,<0.10.0"]
build-backend = "uv_build"
